#!/usr/bin/env bash

# Function to display information about subdomains
display_info() {
    subdomain_info=$(nslookup "$2"."$1" | awk '/^Address: / { print $2 }')
    echo "The subdomain $2 is a A record and points to $subdomain_info"
}

# Main script
if [ "$#" -eq 1 ]; then
    display_info "$1" "www"
    display_info "$1" "lb-01"
    display_info "$1" "web-01"
    display_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
fi
