#!/usr/bin/env bash

# Function to display information about subdomains
display_subdomain_info() {
    domain_info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $domain_info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Main script
if [ "$#" == 1 ]
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}";
    do
        display_subdomain_info "$1" "$subdomain"
    done
elif [ "$#" == 2 ]
then
    display_subdomain_info "$1" "$2"
fi
