#!/usr/bin/env bash
# Install nginx and configures a server to return 'Hello World!'
# +following a GET request

apt-get -y update
apt-get -y install nginx

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

service nginx restart
