#!/usr/bin/env bash
# Install nginx and configures a server to return 'Hello World!'
# +following a GET request

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s|server_name _;|server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/custom_404.html > /dev/null
service nginx restart
