#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Create directory for web content
mkdir -p /data/www

# Create index.html and 404.html files
echo "Holberton School for the win!" > /data/www/index.html
echo "Ceci n'est pas une page, it's a 404!" > /data/www/404.html

# Configure Nginx default server
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    root /data/www;
    error_page 404 /404.html;
    location / {
        index index.html;
        add_header X-Served-By "$HOSTNAME";
    }
    location = /404.html {
        internal;
    }
    location /redirect_me {
        return 301 https://google.com;
    }
}
EOF

# Restart Nginx to apply the changes
service nginx restart
