#!/usr/bin/env bash
# detects what's keeping your Ubuntu container's Nginx installation
# from listening on port 80.

# Remove the existing symbolic link in sites-enabled
sudo rm -f /etc/nginx/sites-enabled/default

# Create a new symbolic link for the default site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
