#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

min=1
hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"

    while [ $min -le 59 ]
    do
        echo "$min"
	((min++))
    done
    
    ((hour++))
    min=1
done
