#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules on web-01

apt-get update
apt-get install ufw
ufw enable
ufw default deny incoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
